set(
    BOARD_DEFS
    # ENABLE_PROTECTIONS
    ENABLE_CHECKSUM
    ENABLE_SAFEWRITE
    # ENABLE_WATCHDOG=20
    ENABLE_GPIO_DFU_BOOT
    GPIO_DFU_BOOT_CUSTOM
    GPIO_DFU_BOOT_PORT=GPIOB
    GPIO_DFU_BOOT_PIN=0
    GPIO_DFU_BOOT_VAL=0
)