set(BOARD $ENV{BOARD})
if("${BOARD}" STREQUAL "")
    set(BOARD "helloword")
endif()
set(BOARD_DIR ${CMAKE_SOURCE_DIR}/boards/${BOARD})
if(EXISTS ${BOARD_DIR}/board.cmake)
    message("Build for board \"${BOARD}\"")
    include(${BOARD_DIR}/board.cmake)
else()
    message(FATAL_ERROR "Board \"${BOARD}\" not found")
endif()
